### ISSUE TITLE
BPE53 support

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#12]
It will be great if you add BEP53 which was added a year ago to `libtorrent` https://github.com/arvidn/libtorrent/pull/2578/commits/d86eec59c6f83b86dd606394f74941329a6a2446. This initiative was made by one of my app users https://github.com/proninyaroslav/libretorrent/issues/119.

**Comment by aldenml** [comment]
Hi @proninyaroslav, here it is a PR to add the support at the java layer (https://github.com/aldenml/libtorrent4j/pull/13), take a look at https://github.com/aldenml/libtorrent4j/pull/13/files#diff-2d945dd95709622de51d030055036487R37

After parsing the magnet and getting the priorities array, you can use it in `SessionManager`.

Also, thanks to this issue I detected an "out-sync" in the priority values.

**Comment by proninyaroslav** [comment]
I will test it soon, thanks.
