### ISSUE TITLE
Downgrade minimum supported Android API version

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#125]
Hi. Is it technically possible to lower the minimum API to at least 19 or 22 or 23? Yes, their number is decreasing, but they still make up a significant percentage of devices, especially 22, not to mention 23.

**Comment by aldenml** [comment]
Hi @proninyaroslav, that I want to try. I might need to bring back some build hacks, but I'm OK with it.

**Comment by aldenml** [comment]
@proninyaroslav can you test in an Android with API=22 as is? The only errors I'm getting are lack of `getifaddrs`, `freeifaddrs` and `fseeko`, but those functions are usually there in bionic.

**Comment by proninyaroslav** [comment]
Hmm, It just crashed with this exception: `java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/aldenml/libtorrent4j`. I use Android x86_64 emulator.

**Comment by aldenml** [comment]
@proninyaroslav, I just released `2.0.0-3` (give it a few minutes to sync in maven), I lowered the API to `21`, but WebTorrent will not work unless the real device has `getifaddrs` and `freeifaddrs` in `libc`.

**Comment by proninyaroslav** [comment]
@aldenml 
Thank you for this information. Later I will test the behavior on API 21.
