### ISSUE TITLE
how to download some piece first ?

### ISSUE THREAD

**Issue by pangoo-reuse** [aldenml/libtorrent4j#133]
hello ，
I want to download some fragments first, for example, I want to download 2-20 blocks first. How can I set up and deal with the download of these fragments first. Thank you.

i try to use 
 ht = torrent_handle 
 th.piecePriority(1, TOP_PRIORITY);
 th.setPieceDeadline(1, 1000);
but ,I don’t quite understand the meaning of these functions, what do these mean, if you can give me an example, thank you

**Comment by aldenml** [comment]
There is no direct control over how the blocks are downloaded. The torrent specifies the blocks per piece and only pieces downloads can be tweaked. By default, pieces are downloaded using a balanced algorithm over the availability reported by peers. `piecePriority` allows you to force certain pieces to be preferred during the entire duration of the download, and `setPieceDeadline` raise the priority of the piece while the deadline hasn't passed. The latter is more suitable for streaming use cases.

I don't have examples in this repo, but you can look at https://github.com/arvidn/libtorrent/blob/RC_2_0/test/test_time_critical.cpp#L58 and https://github.com/arvidn/libtorrent/blob/RC_2_0/test/test_priority.cpp (you will need some C++ familiarity)
