### ISSUE TITLE
help !!! how to setup a special client name?

### ISSUE THREAD

**Issue by pangoo-reuse** [aldenml/libtorrent4j#135]
please help me  !!! how to setup a special client name ?
i found :
        **add_torrent_params p = new add_torrent_params();
        p.setUserdata(new client_data_t());**
but how to set a special name like 'xxx client'

thx a lot.

**Comment by aldenml** [comment]
There are two types of identification for the "client name". The one used for peer-to-peer communication `peer_fingerprint` and by default, starts with `"-LT2000-"`, and the other one used for the user agent while performing HTTP request and by default is `"libtorrent/" LIBTORRENT_VERSION`.

Both of them are changed via `settings_pack` or `SettingsPack` and passed to the session at creation time. If you are using `SessionManager` you can use the `start(SessionSettings)` overload to pass it.
