### ISSUE TITLE
GLIBC_2.29' not found

### ISSUE THREAD

**Issue by WhiteTrashLord** [aldenml/libtorrent4j#145]
I tried the latest version libtorrent4j-2.0.1-7. It didn't start :(
I got this error message on my Ubuntu 18.04 system:

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

Older systems are no longer supported?

**Comment by aldenml** [comment]
ACK, will take a look

**Comment by aldenml** [comment]
Hi @WhiteTrashLord, can you give `2.0.1-7` a try?

**Comment by aldenml** [comment]
sorry, I meant `2.0.1-8`

**Comment by aldenml** [comment]
closing this, feel free to reopen with additional information.

**Comment by WhiteTrashLord** [comment]
I no longer see this error message with a the latest version. But it seems that the java process crashes after a few seconds. I can't find anything in the logs. It's possible that something is wrong with my system or the code. I tried to update glibc which was a terrible idea.

**Comment by aldenml** [comment]
Can you provide the jvm crash log file?
