### ISSUE TITLE
Where is the 32 bit arm and x86?

### ISSUE THREAD

**Issue by master255** [aldenml/libtorrent4j#153]

**Comment by aldenml** [comment]
I imagine you are referring to android (for desktop I only compile `x86_64`), if that's the case, you can grab the jars at:
https://search.maven.org/search?q=a:libtorrent4j-android-arm
https://search.maven.org/search?q=a:libtorrent4j-android-x86
just uncompress the jars and you will find the binaries there.

But, if you are creating a regular APK, the recommended way is to add the dependency in your gradle like
```gradle
implementation 'org.libtorrent4j:libtorrent4j-android-arm:<version>'
```
