### ISSUE TITLE
How to compile it? At least a short instruction?

### ISSUE THREAD

**Issue by master255** [aldenml/libtorrent4j#154]
I have Ubuntu 20.04 LTS. What to do?

**Comment by aldenml** [comment]
If you want to compile this by yourself (for example to have the debug info), the easiest way is to fork and reuse the Github Actions scripts included in this repo in your own account. They store the output once the job is finished and you can download it.

The second option that involves some reading/parsing and looking around is to follow the steps in the script https://github.com/aldenml/libtorrent4j/blob/master/.github/workflows/android.yml#L20.

(In the future, I would like to provide a docker for local compilation with detailed instructions)

**Comment by master255** [comment]
@aldenml Thank you. I didn't know it was possible.
