### ISSUE TITLE
[Question] The size of the .so library has doubled since version 2.0

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#161]
I'm using `libtorrent4j` in the Android project and I noticed that the `.so` size for all architectures has almost doubled in size. What could be the reason for this? Increase in `libtorrent` codebase in the version 2.0?

**Comment by aldenml** [comment]
There are two main reasons for this:
1- The inclusion of `webtorrent` that requires a lot more from `openssl` that I previously disabled during the compilation. This adds a lot.
2- Now I'm compiling with speed optimization (at the cost of bigger binary size).

I understand this is a big inconvenience for distribution outside the Play Store, but the Play Store is getting really smart in terms of delivering only the necessary bits if you allow them to repackage the app.

Open to suggestions on how to improve the overall size.

**Comment by proninyaroslav** [comment]
Yeah, `webtorrent` is most likely to blame. This is generally not critical, it was just interesting to find out the reason.
