### ISSUE TITLE
Bug: Impossible to create a torrent 

### ISSUE THREAD

**Issue by master255** [aldenml/libtorrent4j#163]
@aldenml libtorrent version (or branch): 2.0

platform/architecture: Android

I have a problem.
These lines give an error
byte[] result = builder.generate().entry().bencode();
TorrentInfo torrentInfo = new TorrentInfo(result);

error:
java.lang.IllegalArgumentException: Can't decode data: the v1 and v2 file metadata does not match
at org.libtorrent4j.TorrentInfo.bdecode0(TorrentInfo.java:674)
at org.libtorrent4j.TorrentInfo.(TorrentInfo.java:46)

So what to do? I need to get torrentInfo from byte[]

**Comment by master255** [comment]
Temporary solution:
builder.flags(create_torrent.v2_only);

**Comment by aldenml** [comment]
@master255 something is not right here. Can you provide more information? is this Android 32 bits? How big are the files involved?

**Comment by master255** [comment]
@aldenml I don't know how, but it works now. Even with Listener and without the v1 and v2 flags. Perhaps more information is really needed. I don't know how this is possible.
I will open it if it happens again.

**Comment by master255** [comment]
@aldenml This file gives an error:
```
2021-03-06 17:03:33.552 31256-31256 W/System.err: java.lang.IllegalArgumentException: Can't decode data: one or more files are missing piece layer hashes
2021-03-06 17:03:33.553 31256-31256 W/System.err:     at org.libtorrent4j.TorrentInfo.bdecode0(TorrentInfo.java:674)
2021-03-06 17:03:33.554 31256-31256 W/System.err:     at org.libtorrent4j.TorrentInfo.bdecode0(TorrentInfo.java:657)
2021-03-06 17:03:33.554 31256-31256 W/System.err:     at org.libtorrent4j.TorrentInfo.<init>(TorrentInfo.java:34)
```


[shared.zip](https://github.com/aldenml/libtorrent4j/files/6095430/shared.zip)

**Comment by master255** [comment]
This code:

final TorrentBuilder builder = new TorrentBuilder();
                    builder.path(pathFile);
                    builder.comment(createParams.getComment());
                    builder.creator("creator");
                    builder.setPrivate(false);
                    String[] trackers = (String[]) Constants.trackers.toArray();
                    for (String tracker : trackers)
                        builder.addTracker(tracker);
                        byte[] result = builder.generate().entry().bencode();
                        TorrentInfo torrentInfo = new TorrentInfo(result);

Gives this error:

2021-03-06 17:30:09.750 5042-6313 W/System.err: java.lang.IllegalArgumentException: Can't decode data: the v1 and v2 file metadata does not match
2021-03-06 17:30:09.753 5042-6313 W/System.err:     at org.libtorrent4j.TorrentInfo.bdecode0(TorrentInfo.java:674)
2021-03-06 17:30:09.753 5042-6313 W/System.err:     at org.libtorrent4j.TorrentInfo.<init>(TorrentInfo.java:46)

Android 26api arm 64

**Comment by aldenml** [comment]
Give me some time to look into this.

**Comment by aldenml** [comment]
@master255 inside the file, there are two files with non-ascii charaters. My macOS unzip is not recognizing those names correctly. Do you mind testing again with ascii only name files? Android natively works with UTF-8 and I just want to start discarding possibilities.

**Comment by master255** [comment]
@aldenml ok

**Comment by master255** [comment]
@aldenml I don't know what it depends on. Right now creating a torrent from these files works. But creating a torrent from the Telegram directory gives me the same error again. 
Some kind of unstable work.

**Comment by aldenml** [comment]
@master255 we need to continue discarding variables. There is a big difference in how the files are handled by default between Android 32 bits and 64 bits. Do you mind performing the tests on a 32 bits device?

**Comment by master255** [comment]
@aldenml What for? I have a problem at Android 26api arm 64 . How does the 32 bit test help us? You can check it yourself with an x86 emulator.

**Comment by aldenml** [comment]
Because if you don't get the problem (after multiple tests) in Android 32 bits, then I have a hint of what could be the issue (posix storage vs mmap). (yes, I can test,  but it will take more time)

**Comment by master255** [comment]
@aldenml I just checked. It is impossible to reproduce in x86 and x64 emulator. But it constantly reproduces on a real Android 26api arm-64 phone.
I am doing the same thing. I copy one directory and try to create a torrent.

**Comment by master255** [comment]
@aldenml Okay. On my Xaomi Redmi Android 10 there is no this bug too. Bug is present on Samsung Galaxy s8+ Android 8.0.

**Comment by master255** [comment]
@aldenml I will leave the torrents 2.0 player branch for tests. Now I switch back to torrents 1.2.12. There are too many bugs to use version 2.0 now. When these are resolved I will upgrade to 2.0.

**Comment by dyorgio** [comment]
TransmissionBT only accepts torrent files created with create_torrent.v1_only flag on 2.0.4-21 version

**Comment by aldenml** [comment]
Hi @dyorgio, is TransmissionBT based on `libtorrent4j`?

**Comment by dyorgio** [comment]
No, TransmissionBT is a QT client I guess...
I'm only documenting it here, because I get stucked in this error for some days, until I found this Issue.
If I use 1.2.3-0 version of libtorrent4j, created torrent file is readed by TransmissionBT without any additional flag.

**Comment by aldenml** [comment]
I see, thank you for the report.

**Comment by master255** [comment]
not actual
