### ISSUE TITLE
Speed up local android builds

### ISSUE THREAD

**Issue by aldenml** [aldenml/libtorrent4j#167]
```
You can pass -j4 and build faster if when you invoke docker run you pass the option --cpus 4
```
thanks @gubatron

**Comment by gubatron** [comment]
Just wanted to come and share that I'm finally done with a Dockerized build process for jlibtorrent, feel free to reuse it for libtorrent4j, this is simply amazing. What a game changer. I will Dockerize all the things from now on.

https://github.com/frostwire/frostwire-jlibtorrent#building
