### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.libtorrent4j.alerts.AlertType.ordinal()' on a null object reference

### ISSUE THREAD

**Issue by etring** [aldenml/libtorrent4j#177]
I got a fatal exception, here is the log:
I use version "2.0.3-17"

 E/AndroidRuntime: FATAL EXCEPTION: SessionManager-alertsLoop
    java.lang.NullPointerException: Attempt to invoke virtual method 'int org.libtorrent4j.alerts.AlertType.ordinal()' on a null object reference
        at org.libtorrent4j.SessionManager$5.run(SessionManager.java:1170)
        at java.lang.Thread.run(Thread.java:919)

I debug it, and get the alert.type() is 97
then I check the source code in  https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/alert_types.hpp
There is a alert named "TORRENT_DEFINE_ALERT(file_prio_alert, 97)"
It seems something wrong with the alert type 97

**Comment by aldenml** [comment]
@etring thanks for this report, I can confirm this is a bug, I will release a new version with the fix today

**Comment by etring** [comment]
already fixed in version 2.0.3-18
