### ISSUE TITLE
Create Torrent (Bittorrent V2 - Hybrid) with pre calculated piece hashes

### ISSUE THREAD

**Issue by rpithadia25** [aldenml/libtorrent4j#182]
Hey Alden,

I have a scenario where I have pre calculated piece hashes for a particular file (using SHA-256).
Now I want to be able to create a torrent file using the existing piece hashes.
I saw the tests and only see examples to create torrents using either file, directory or the TorrentBuilder. But I'm not sure any of these methods would allow me to pass/set my own piece hashes.
Could you please advice if there is a workaround for my use case?

Thanks in advance!

**Comment by aldenml** [comment]
Hi @rpithadia25, `TorrentBuilder` was meant to address the simple cases with a fluent api. Here I added a verbatim copy of a test in `libtorrent` for a `v2` only https://github.com/aldenml/libtorrent4j/pull/183, something similar can be done for hybrid.
```java
error_code ec = new error_code();
file_storage fs = new file_storage();
fs.add_file_ex(ec, "test/A", 0x8002);
fs.add_file_ex(ec, "test/B", 0x4002);
create_torrent t = new create_torrent(fs, 0x4000, create_torrent.v2_only);

t.set_hash2(0, 0, sha256_hash.max());
t.set_hash2(0, 1, sha256_hash.max());
t.set_hash2(0, 2, sha256_hash.max());
// file 1 is a pad file
t.set_hash2(2, 0, sha256_hash.max());
t.set_hash2(2, 1, sha256_hash.max());

byte[] buffer = Vectors.byte_vector2bytes(t.generate().bencode());
torrent_info info = TorrentInfo.bdecode(buffer).swig();
assertTrue(info.info_hashes().has_v2());
assertFalse(info.info_hashes().has_v1());
assertEquals("A", info.files().file_name_ex(0));
assertTrue(info.files().pad_file_at(1));
assertEquals("B", info.files().file_name_ex(2));
assertEquals("test", info.name());

create_torrent t2 = new create_torrent(info);
byte[] buffer2 = Vectors.byte_vector2bytes(t2.generate().bencode());
assertArrayEquals(buffer, buffer2);
```
let me know if there is another specific case I can help with.

**Comment by rpithadia25** [comment]
Thanks a lot for the quick response. I'll try this out.
