### ISSUE TITLE
Restrict peer communication to subnet

### ISSUE THREAD

**Issue by rpithadia25** [aldenml/libtorrent4j#185]
Hey Alden,

Is there a way to restrict peer communication to a particular subnet.
For my use case, I want the client (peer) to block any communication with another peer not within a subnet.
I found "listen_interfaces" and "outgoing_interfaces" looking at the libtorrent documentation.
Is there a way for me to initialize the SessionManager specifically for a subnet?

**Comment by aldenml** [comment]
Hi @rpithadia25 sorry for the delay. The way `libtorrent` works is that it listens to interfaces, here it is a code extracted from one of the demos:
```java
SettingsPack sp = new SettingsPack();
//sp.listenInterfaces("0.0.0.0:43567");
//sp.listenInterfaces("[::]:43567");
//sp.listenInterfaces("0.0.0.0:43567,[::]:43567");
//sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.silotis.us:6881");
//sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.bittorrent.com:6881");
//sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "dht.transmissionbt.com:6881");

SessionParams params = new SessionParams(sp);

s.start(params);
```
to pass any setting to `SessionManager`.

But if you want to work with a subnet (strictly) of such interface, you need to work with `ip_filter`. There is no high-level Java api for this but you can get to it via `.swig()` calls.

**Comment by rpithadia25** [comment]
Thanks for the response Alden!

**Comment by rpithadia25** [comment]
Hey Alden,

One quick question regarding ip_filter. 
Is the filter supposed to block the IPs that are added to it?
I’m trying to understand whether it behaves as a allow/deny list.

**Comment by rpithadia25** [comment]
Hey Alden,

When I set the ip_filter to accept a range of IPs. Does that mean, the client will reject connections from IPs outside this range?

Basically, i'm doing this:

filter.add_rule(firstAddr, lastAddr, 0);

Was curious whether the filter now blocks every other IP outside this range (i.e. ip < firstAddr and ip > lastAddr).

**Comment by aldenml** [comment]
I never used `ip_filter`, but it should work similarly to `port_filter`, blocking connections to those IPs/ports.

**Comment by rpithadia25** [comment]
Oh ok.. but when we add certain ports to the "allowed" list i.e. instead of port_filter::blocked we do port_filter::allowed (which  basically translates to long 0), does this mean it will allow only those ports and block the others?
Basically I'm trying to use ip_filter as an allow list instead of a block list :)

**Comment by aldenml** [comment]
can't say for sure, never used it :)

**Comment by rpithadia25** [comment]
Oh ok.. thanks for the quick responses :)
Will try running a couple tests.

**Comment by rpithadia25** [comment]
Hey Alden,

Just to conclude. I was able to achieve the "allowed" list behavior.

Example:
ip_filter ipFilter = new ip_filter();

// Block all IPs
filter.add_rule("0.0.0.0", "255.255.255.255", ip_filter.access_flags.blocked.swigValue());

// Add specific IPs to allow. (long value 0 is to allow)
filter.add_rule("192.168.1.1", "192.168.1.10", 0);

So basically block all the IPs first and then selectively add the ranges you want to allow :)

Thanks for pointing me in the right direction!

**Comment by aldenml** [comment]
great!!
