### ISSUE TITLE
[Help] Libtorrent implement http servee

### ISSUE THREAD

**Issue by VuzzyM** [aldenml/libtorrent4j#186]
@aldenml 
Hello.

Sorry to bother you. Want me to ask if you don't want to try implementing libtorrent in the new torrent server? Unfortunately YouROK doesn't have time for implementation right now, libtorrent engine is better than anacrolix engine.

Source code for Torrserver Matrix, stream torrent server http:
https://github.com/YouROK/TorrServer

Thank you for the help.

**Comment by aldenml** [comment]
Hi @VuzzyM, I don't have `go` lang experience and have no time for another open-source project.
