### ISSUE TITLE
Restrict announce on multiple interfaces

### ISSUE THREAD

**Issue by rpithadia25** [aldenml/libtorrent4j#188]
Hi Alden,

Is there a way to restrict the libtorrent4j client to not announce on multiple addresses?
Basically I'm seeing multiple simultaneous announces on the tracker and want to restrict the client to not do so.
Maybe there is a settings_pack value that I can set?
 
Appreciate your help!

**Comment by aldenml** [comment]
I think there is something about it, but need to revisit the code around that part. Since this is a question regarding `libtorrent`, you can also put the question there, and maybe someone can reply to you sooner.

**Comment by rpithadia25** [comment]
Thanks Alden, will do :)
