### ISSUE TITLE
Segmentation fault on downloading using DownloadTorrent demo code

### ISSUE THREAD

**Issue by mikedawson** [aldenml/libtorrent4j#189]
Hi,

I'm trying to use libtorrent4j on a JVM server and Android. Most smaller torrents download OK. However 100MB+ torrents seem to cause a segmentation fault. eg Downloading the [Libreoffice torrent](https://fosstorrents.com/softwares/libre-office/#downloads) from FossTorrents:

```
samih@samih-Lenovo-ideapad-520-15IKB:~/src/libtorrent4j$ java -Xmx5120M -verbose:gc -classpath build/libs/libtorrent4j-2.0.4-21.jar:demo/build/libs/demo.jar org.libtorrent4j.demo.DownloadTorrent /home/samih/Downloads/LibreOffice_7.1.5_Win_x64.msi.torrent Progress: 91 for torrent name: LibreOffice_7.1.5_Win_x64.msi
....
Progress: 91 for torrent name: LibreOffice_7.1.5_Win_x64.msi
318073981
Progress: 91 for torrent name: LibreOffice_7.1.5_Win_x64.msi
318073981
Segmentation fault (core dumped)
```

This is using OpenJDK11 on Ubuntu. Java version as follows:

```
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

I can't find the actual core dump file (e.g. hs_err etc). I tried increasing the memory allocated using the Xmx parameters, that doesn't seem to change it. The segmentation fault doesn't always happen at the same time, but it does happen most of the time.

Is there something we can do to get the actual dump to further debug what is going on here?

Thanks!

**Comment by aldenml** [comment]
Hi @mikedawson, give me some time to spin up a VM and try to replicate the issue. Can you provide the version of `libtorrent4j` you are using?

**Comment by mikedawson** [comment]
Hi @aldenml ,

Thanks for the quick reply. I'm using the latest source from master. My git log shows:

```
commit e91b5b4cb651615075ccd122d922886f64f63dfd (HEAD -> master, tag: v2.0.4-21, origin/master, origin/HEAD)
Author: Alden Torres <aldenml@gmail.com>
Date:   Sun Jul 25 18:40:41 2021 -0400

    update to libtorrent master HEAD, version 2.0.4-21 (#187)

```

I tried looking for ways to get the actual segmentation fault dump, but I'm not that familiar with debugging C. If there is something I should do to try and get more debugging output, let me know and I'll do so.

**Comment by aldenml** [comment]
Hi @mikedawson, sorry for the big delay. I finally managed to test on my side, and I can tell you I tried multiple times with the same torrent and it all seems to be working fine:
<img width="1159" alt="Screen Shot 2021-08-14 at 2 34 26 PM" src="https://user-images.githubusercontent.com/143813/129457062-073ed0d3-95a7-4d05-b0d5-b45655acfb93.png">
Can you provide more details of your setup, like total RAM memory, free disk space, etc. Also, having that hs_err file helps a lot. (and thanks for reporting this)

**Comment by aldenml** [comment]
stale, no details provided
