### ISSUE TITLE
after the new update to libtorrent4j v2.x it's working with low download speed

### ISSUE THREAD

**Issue by ofirkris** [aldenml/libtorrent4j#190]
I've compared an android build i've used for months of v1.x and v2.x and there's a huge speed difference in the favor of the older version 1.x - any way to fix this?

**Comment by aldenml** [comment]
It's _not_ supposed to be that way, and this is the first complaint about speed. Can you provide some numbers and data to compare? Thanks.

**Comment by aldenml** [comment]
@ofirkris I read the reviews and the references to the download speed. Without being able to replicate the issue with a concrete example (i.e. a particular torrent) this is almost impossible to troubleshoot. Do you experience this speed slow down in your devices?

**Comment by ofirkris** [comment]
@aldenml This is indeed nearly impossible to troubleshoot, It was indeed slower for me too. I can run a comparison of old apk vs the new version - but what will this tell us exactly? I have no idea how to fix this issue..

**Comment by aldenml** [comment]
Send me a (safe) torrent that with the old version is faster and significantly slower in the new one. I will try to replicate it on my side.

**Comment by aldenml** [comment]
stale, no additional information was provided
