### ISSUE TITLE
Disk writes after download complete?

### ISSUE THREAD

**Issue by rpithadia25** [aldenml/libtorrent4j#191]
Hey @aldenml,

I have the following scenario for my application:
1. Download a torrent using libtorrent4j and keep the SessionManager active (keep seeding).
2. Read the downloaded file from disk and create a stream from it. 

This works fine for smaller files like 10 MB or 100 MB.

However, for larger files, I see intermittent exceptions while reading the stream.

I do not observe this when I stop the session (no seeding) before reading the file to stream.

I feel this might be because the stream and session manager are both accessing the file together?

**Question:** Does the session manager still write to the file after download has finished? Currently I use the TORRENT_FINISHED alert to determine when to return control back to the code to create the stream. 

As a work around, I'm stopping the session once the download completes and then restart it after the stream has been created. But I'm sure there could be a better way to handle this.

Appreciate your help!

**Comment by aldenml** [comment]
Good to know, thank you for document this!
