### ISSUE TITLE
Unable to download torrent on Android 11 (API 30)

### ISSUE THREAD

**Issue by anantadwi13** [aldenml/libtorrent4j#195]
I have a problem when using API level 30. Libtorrent4j seems not working on it. When I start a new session, it doesn't listen to any network. Below are logs from the torrent alert.

```
LOG - log - start session
LOG - log - version: 2.0.4.0 revision: f9836137a
LOG - log - max-connections: 200 max-files: 32768
LOG - log -  *** session thread init
LOG - log -  done starting session
LOG - log - RECALCULATE UNCHOKE SLOTS: [ peers: 0 eligible-peers: 0 allowed-slots: 8 ]
LOG - log - update listen interfaces: 0.0.0.0:6881,[::]:6881
LOG - log - parsed listen interfaces count: 2, ifaces: 0.0.0.0:6881,[::]:6881
LOG - log - not starting DHT announce timer: m_dht == nullptr
LOG - log -  *** session paused ***
LOG - log - about to stop DHT, running: false
LOG - log - starting DHT, running: false, router lookups: 0
```

This won't happen when I'm running my app on Android 10 devices or using API 29.

I found this in another discussion. It might help. https://stackoverflow.com/questions/64884994/cannot-bind-netlink-socket-when-targeting-android-api-30

Thanks.

**Comment by aldenml** [comment]
Hi @anantadwi13 , thanks for the report, I'm aware of the issue and I have plans to fix it soon, unfortunately, I can't give you an ETA.

**Comment by anantadwi13** [comment]
It's ok. Thank you for your response.

**Comment by qyzhaojinxi** [comment]
I met this problem too. I'm looking forward to a quick resolution.

**Comment by aldenml** [comment]
@gubatron I tried to apply the patch that you posted in https://github.com/arvidn/libtorrent/issues/6251#issuecomment-897994223, but for some reason, DHT seems to not work. Does this sound familiar?

**Comment by gubatron** [comment]
@aldenml did you also update the SDK versions of the toolchains to be api 24?

```
RUN cd /src \
    && android-ndk/build/tools/make_standalone_toolchain.py --arch arm --api 24 --stl libc++ --install-dir android-toolchain-arm \
    && android-ndk/build/tools/make_standalone_toolchain.py --arch arm64 --api 24 --stl libc++ --install-dir android-toolchain-arm64 \
    && android-ndk/build/tools/make_standalone_toolchain.py --arch x86 --api 24 --stl libc++ --install-dir android-toolchain-x86 \
    && android-ndk/build/tools/make_standalone_toolchain.py --arch x86_64 --api 24 --stl libc++ --install-dir android-toolchain-x86_64
```
also, there were a bunch of `sed` replacements that I got rid of for those API numbers as I upgraded to API 24.

Other than that no issues for me connecting to DHT.

I'm still having a nasty crash on arm32 bit on a real device that AT&T started giving out for free to people (I believe it runs Android 10 or 11), been trying to fix it for weeks now, having trouble to get a debugger on Android SDK to let me step down to C++, I've decided I will release as is and hopefully upload the symbol's file for arm32 to have some light of why it's crashing, this is the only instance where I can't get DHT to work because nothing works.

**Comment by proninyaroslav** [comment]
@aldenml 
I get this on some real devices, although I can't reproduce it on an emulator:
```
LISTEN_FAILED - listen_failed - listening on 0.0.0.0:0 (device: ) failed: [enum_if] [TCP] Permission denied
```

**Comment by aldenml** [comment]
Hi @proninyaroslav, I think we are close to a deadline or something regarding this new restriction. I tried to fix it the past weekend but I'm not there yet. What's your position on dropping support for API < 24?

**Comment by proninyaroslav** [comment]
@aldenml 
Thank you for your work. I looked at Google Play statistics and the number of active installations with API 21-23 is about 2.4% of the total number of installations (and 3% of all installations/uninstallations). This doesn't take into account installs from third-party sources and F-Droid (there will probably be more). This seems like a small number, but this is 2000-3000 people who will be left without support. I've always found it difficult to take such a step, so I'll leave it up to you. If API <24 support is burdensome or impossible, then you are free to up the API version.

**Comment by gubatron** [comment]
from what I'm seeing here at jlibtorrent we had to make that decision. API 23 and under is at least 4 years old, plenty of time to upgrade for most people, and those that can't afford an update can still use older clients which will work decently as they have up to now given the stability of libtorrent.

**Comment by aldenml** [comment]
@proninyaroslav thank you very much for sharing the information. I will make the hard decision and go ahead removing support for API < 24.

**Comment by aldenml** [comment]
With https://github.com/aldenml/libtorrent4j/pull/198 I released `2.0.4-22-RC1`, already in maven, please, give it a try.

**Comment by anantadwi13** [comment]
> With #198 I released `2.0.4-22-RC1`, already in maven, please, give it a try.

LGTM. It's running well using API 31 on Android 8.1 and Android 11 real devices. Thank you for your hard work! @aldenml @gubatron

**Comment by proninyaroslav** [comment]
This seems to be fixed, I haven't encountered this error.

**Comment by aldenml** [comment]
@proninyaroslav thanks for reporting back.
