### ISSUE TITLE
[Android] NTFS/exFAT is unsupported: (1) Operation not permitted [write : file_open]

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#201]
I got this from a user of my app. libtorrent4j `2.0.4-21` is used here. So far I can't test it with `2.0.4-22-RC1`, but there will be a release soon. He uses NTFS for SD card on Android 11. At the same time, he can download to the internal storage without any problems:
`disk error: (1) Operation not permitted [write : file_open] in file: /storage/B8CCF31FCCF2D69A/Download/***`

Full log:
[LibreTorrent_log_11-29-2021_12-36-35.txt](https://github.com/aldenml/libtorrent4j/files/7617256/LibreTorrent_log_11-29-2021_12-36-35.txt)

**Comment by aldenml** [comment]
Is NTFS supported in Android already?

**Comment by proninyaroslav** [comment]
I don't know about AOSP, but many firmwares have NTFS support.

**Comment by proninyaroslav** [comment]
@aldenml 
As it turned out, `libtorrent4j` has problems not only with NTFS, but also with exFAT https://gitlab.com/proninyaroslav/libretorrent/-/issues/384#note_817005551. As I found out, `sdfat` is the old name of the exFAT driver in Android.

**Comment by proninyaroslav** [comment]
This seems to be a bug on the Android Framework side. The system gives incorrect information about the write permission.

**Comment by aldenml** [comment]
This was my thinking, the way they manage the access at the process layer is really complicated.

**Comment by proninyaroslav** [comment]
Yeah, actually it's weird, the permission check sometimes fails.
