### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by Sumandora** [aldenml/libtorrent4j#207]
Is there a way to use proxies when downloading?
LibTorrent references proxies in the source code (https://github.com/arvidn/libtorrent/blob/RC_2_0/src/proxy_settings.cpp), so I think they are a feature. Am I not looking right and if so, how would you go about using them?

**Comment by aldenml** [comment]
Hi @Sumandora, you can use the `SessionManager.start(SessionParams params)` method. Before calling it, create a `SessionParams` and adjust the inner session pack. Here is an example of how it's used internally:
https://github.com/aldenml/libtorrent4j/blob/master/src/main/java/org/libtorrent4j/SessionManager.java#L140-L148

**Comment by Sumandora** [comment]
Thank you very much.
I'm implemented proxies and it works perfectly.
Thanks for your quick response and excellent help! :)
