### ISSUE TITLE
[Android] "FILE_TRUNCATE Operation not permitted" on ARM64 only

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#211]
Redirected from https://github.com/arvidn/libtorrent/issues/6750

One of my users collided with the following situation: it uses a tablet with SOC AllWinner A133 (arm64) and Android 11. Apparently, this doesn't affect all SoC's, as some users didn't come across this problem. My app uses access to all files (`MANAGE_EXTERNAL_STORAGE` permission is used in accordance with Android 11+ limitations).
When he tries to download any torrent on SD card, then he gets this error: [FILE_TRUNCATE] Operation not permitted, code 1, If he install the APK version for arm64 (I'm using [libtorrent4j](https://github.com/aldenml/libtorrent4j) builds). If he install the armeabi-v7a version of the APK, then the downloading is successful.
The SD card file system is exFAT, because exFAT has become a standard solution for SD cards in recent versions of Android (in the form of the sdfat driver).
The problem is manifested exclusively with arm64 library, although it successfully uses armeabi-v7a version without any errors.

libtorrent developers commented on the situation and offer to use posix disk back-end, instead of mmap https://github.com/arvidn/libtorrent/issues/6750#issuecomment-1052557999

**Comment by aldenml** [comment]
Hi @proninyaroslav, it is really good that @arvidn proposed a solution already. I will not have time until later this week, but it l think it should be a relatively quickly change.

**Comment by aldenml** [comment]
Hi @proninyaroslav, working in this with https://github.com/aldenml/libtorrent4j/pull/212

**Comment by aldenml** [comment]
@proninyaroslav I just published `2.0.5-26-RC1` for you to test. Now you can call `SessionParams#setPosixDiskIO()` to set to posix and `SessionParams#setDefaultDiskIO()` to revert. Let me know how it goes.

**Comment by proninyaroslav** [comment]
@aldenml 
Thank you, today I will release a beta version so that who came across this problem, they could test it.

**Comment by proninyaroslav** [comment]
@aldenml 
I need your advice: should I enable posix by default, or should I make an option and only recommend enabling it to those who are having problems with FS? I'm concerned that enabling posix can affect download performance and reliability

**Comment by aldenml** [comment]
@proninyaroslav I think using posix is a sensible default in android. It's a highly fragmented platform and high performance is not in play (since you have java in the middle :).

You can still expose the option in your settings for advanced users to be able to select mmap.

**Comment by proninyaroslav** [comment]
@aldenml 
I received feedback from the user who encountered the original problem. He said that now it's fixed. I also start public testing to make sure that posix didn't break anything. I think for a week I will collect enough information to release a new, non-beta version with posix disk io.

**Comment by proninyaroslav** [comment]
@aldenml 
So, no problems found.
