### ISSUE TITLE
Nothing compiles

### ISSUE THREAD

**Issue by master255** [aldenml/libtorrent4j#220]
@aldenml Where are the libtorrent and boost installation commands?
Docker gives an error when creating it. There are errors everywhere.
Maximum of where I've gone:
![image](https://user-images.githubusercontent.com/5380115/166810836-50692019-a2fc-4cb1-9d2e-768ef3eabd5c.png)

**Comment by aldenml** [comment]
@master255 I understand documentation is not great for out-of-docker compilation, everything is coded in the GitHub Actions files, can you look there?

**Comment by master255** [comment]
@aldenml Ok. I see. But how to convert this to the Docker script?
