### ISSUE TITLE
Start a task with Resume file take too much time

### ISSUE THREAD

**Issue by Jason-wam** [aldenml/libtorrent4j#224]
When start a task with a Resume file，sometimes it take too much time (Occasionally even more than 20 seconds)。
but i don't know why it happens。

``session.download(torrentInfo, downloadFile, resumeFile, selection.toTypedArray(), null, flags)
``

Thanks for this library！

**Comment by 471448446** [comment]
检查下`SessionManager.start()`调用了没有

**Comment by Jason-wam** [comment]
> 

调用了的，是存在延迟启动完毕吗

**Comment by Jason-wam** [comment]
I solved it with ``session.swig().async_add_torrent(addTorrentParams)``，thanks for your attention
