### ISSUE TITLE
Info about the docs

### ISSUE THREAD

**Issue by drakonkat** [aldenml/libtorrent4j#227]
There is no documentation on how to use it? There is some open source implementation of this library?

**Comment by aldenml** [comment]
hi @drakonkat, I can point you to good resources and practical examples.

from this project:
https://github.com/aldenml/libtorrent4j/tree/master/demo/src/main/java/org/libtorrent4j/demo
https://github.com/aldenml/libtorrent4j/tree/master/src/test/java/org/libtorrent4j/demo

LibreTorrent: https://github.com/proninyaroslav/libretorrent

and if you want to use the low level api (close to the cpp code):
http://libtorrent.org/tutorial-ref.html
http://libtorrent.org/examples.html
