### ISSUE TITLE
Tracker over ssl not working

### ISSUE THREAD

**Issue by aldenml** [aldenml/libtorrent4j#23]
@WhiteTrashLord I can confirm the issue https://github.com/frostwire/frostwire-jlibtorrent/issues/213, still figuring out if it's in my `libtorrent` build with the specific `openssl`

**Comment by WhiteTrashLord** [comment]
@aldenml 
I think I found a possible problem. Does your openssl library support Server Name Indication (SNI) ?
Do you build openssl with tlsext?

**Comment by aldenml** [comment]
I just tested with an `openssl` build without any disable flag (plain `./Configure`) and still fails. The tracker sends `d14:failure reason9:Error 027e`

**Comment by aldenml** [comment]
Well, I found the reason in my case. I was testing with the default port `6881` and it was not working. Then I switched to a random assigned port and started to download. This is the code:
```java
SettingsPack sp = new SettingsPack();
sp.setString(settings_pack.string_types.listen_interfaces.swigValue(), "0.0.0.0:0,[::]:0");
SessionParams params = new SessionParams(sp);

sessionManager.start(params);
```
Let me know if you can test with that

**Comment by WhiteTrashLord** [comment]
With this setting it's really working now! :) But I don't understand the reason. Is the tracker blocking the standard port? qBittorrent uses this setting by default?

**Comment by WhiteTrashLord** [comment]
With this setting it's working with 1.2.0.18 for me. With your latest 1.2.0.20-RC3 it's no longer working here :( Did you make another change there?

**Comment by aldenml** [comment]
No idea what's the issue with the port and the tracker, but at least it's not the `openssl` integration :)

**Comment by WhiteTrashLord** [comment]
Thank you very much for your help :)

**Comment by WhiteTrashLord** [comment]
Yes, please close it :)
