### ISSUE TITLE
How to create torrents from torrent info 

### ISSUE THREAD

**Issue by 471448446** [aldenml/libtorrent4j#263]
Hi, how can i get ByteArray from TorrentInfo that already exists

before 2.1.0-27:

```kotlin
val ti = org.libtorrent4j.TorrentInfo(file);
val ba:ByteArray = ti.bencode();
```

`bencode()` and `toEntry()` has been removed. [update to libtorrent master HEAD, version 2.1.0-27](https://github.com/aldenml/libtorrent4j/commit/e99906b3bacbd5a396c56e240bdbfd5f0b8df7b5#diff-46363c38427ff4a7a40231266b66c9395e321c132f8ac662cbdbc79299d876bc)

**Comment by aldenml** [comment]
Hi @471448446, those functions were considered unnecessary in upstream `libtorrent`. From you code, if you have access to the file, you can parse it with `BDecodeNode`. Maybe you can elaborate more on your use case.

**Comment by 471448446** [comment]
In my case, i just want to save the TorrentInfo obtained elsewhere to a local file

```kotlin
// get TorrentInfo from uri
fun getTorrentInfo(uri:Uri):org.libtorrent4j.TorrentInfo{
    //...
    val byteData = SessionManager.get().fetchMagnet(uri, timeout, tempDir)
    return TorrentInfo.bdecode(byteData)
}
// save TorrentInfo to file
fun saveTorrentInfo(ti:org.libtorrent4j.TorrentInfo,torrentFile:File){
    val ba:ByteArray = ti.bencode()
    // a function save byte info to file. just ignore.
    saveTorrent(byteArray, torrentFile)
}
```

I modified the logic. Any TorrentInfo that has been obtained is saved to a temporary file first. This avoids the need to directly operate the TorrentInfo API to save the file.

thank you! @aldenml 

> Hi @471448446, those functions were considered unnecessary in upstream `libtorrent`. From you code, if you have access to the file, you can parse it with `BDecodeNode`. Maybe you can elaborate more on your use case.
