### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#267]
There have been no updates for a long time, and critical errors have not been fixed. Maybe someone forked the project or found a maintainer? It's sad :(

**Comment by aldenml** [comment]
Hi @proninyaroslav , I totally understand your question due to my lack of activity here, but I have no plans to abandon this project. I have been very busy with my everyday work. Hopefully I can find some time in the coming weeks!

**Comment by proninyaroslav** [comment]
OK, thank you!
