### ISSUE TITLE
TorrentFlags.NEED_SAVE_RESUME doesn't work properly

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#44]
Hi. Perhaps this flag works in a different way, but after adding the torrent, it doesn't trigger the `SAVE_RESUME_DATA` alert (I use latest `libtorrentj` version). I made an example to check it:

```Java
File torrentFile = new File("path_to_torrent");

SessionManager s = new SessionManager();
s.addListener(new AlertListener() {
    @Override
    public int[] types() {
        return null;
    }

    @Override
    public void alert(Alert<?> alert) {
        AlertType type = alert.type();
        switch (type) {
            case ADD_TORRENT:
                System.out.println("Torrent added");
                break;
            case SAVE_RESUME_DATA:
                System.out.println("Do save resume");
                break;
        }
    }
});

s.start();

TorrentInfo ti = new TorrentInfo(torrentFile);

add_torrent_params p = add_torrent_params.create_instance();
p.set_ti(ti.swig());
p.setSave_path(torrentFile.getParent());

torrent_flags_t f = p.getFlags();
f = f.or_(TorrentFlags.NEED_SAVE_RESUME);
f = f.and_(TorrentFlags.PAUSED.inv());
p.setFlags(f);

s.swig().async_add_torrent(p);

System.in.read();
```

**Comment by aldenml** [comment]
Hi @proninyaroslav, the flag `NEED_SAVE_RESUME` is set by default, but his only purpose is to force to `needSaveResumeData` returns `true`. If you intend to save periodically the resume data, you should call `needSaveResumeData` to see if indeed it's necessary for that torrent. Now, to get and save the resume data, you should call `saveResumeData` and this call is the one that generates the alert with type `SAVE_RESUME_DATA`.

See:
https://github.com/frostwire/frostwire/blob/master/common/src/main/java/com/frostwire/bittorrent/BTDownload.java#L634
https://github.com/frostwire/frostwire/blob/master/common/src/main/java/com/frostwire/bittorrent/BTDownload.java#L719

**Comment by proninyaroslav** [comment]
Thank you for explaining!
