### ISSUE TITLE
libtorrent4j is still maintained?

### ISSUE THREAD

**Issue by WhiteTrashLord** [aldenml/libtorrent4j#46]
I had a torrent which was not working with the latest version of libtorrent4j.
With the latest version of frostwire-jlibtorrent the torrent was working fine.
Will there be new versions of libtorrent4j?
I can send details about the not working torrent via email.

**Comment by aldenml** [comment]
Hi @WhiteTrashLord, yes its, or at least is my intention :) Can you provide the exact versions of `jlibtorrent` and `libtorrent4j` that you are using?

**Comment by WhiteTrashLord** [comment]
libtorrent4j 1.2.1.0 and jlibtorrent 1.2.1.0

**Comment by aldenml** [comment]
@WhiteTrashLord I just updated the build to use libtorrent 1.2.2 and published it to maven. Let me know if you need a release with the fixes (they are minor) after the release tag of 1.2.2.
