### ISSUE TITLE
[TorrentBuilder] Incorrect work with Storage Access Framework

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#47]
Hi. As I said earlier, I use POSIX wrapper to work with SAF. There is one bug, if I put SAF's path to `TorrentBuilder` (for example `com.android.externalstorage.documents/tree/0FED-1B0/`):
```
java.io.IOException: content total size can't be 0
        at org.libtorrent4j.TorrentBuilder.generate(TorrentBuilder.java:488)
```
although the dir isn't empty. Before this exception, the only call of `stat("com.android.externalstorage.documents/tree/0FED-1B0/")` method happens and no more calls before and after this:
```Java
@Override
public int stat(String path, posix_stat_t buf)
{
    if (isFileSystemPath(path))
        return super.stat(path, buf);

    SafFileSystem.FakePath fakePath = ...;

    SafFileSystem.Stat stat = fs.stat(fakePath);
    if (stat == null) {
        ...
    }

    int S_ISDIR = stat.isDir ? 0040000 : 0;
    int S_IFREG = 0100000;

    buf.setMode(S_ISDIR | S_IFREG);
    buf.setSize(stat.length);
    int t = (int)(stat.lastModified / 1000);
    buf.setAtime(t);
    buf.setMtime(t);
    buf.setCtime(t);

    return 0;
}
```
Also `fs.stat()` returns `length = 512` and `isDir = true` for SAF dir `com.android.externalstorage.documents/tree/0FED-1B0/`. I made it similar to the code example from Frostwire: [AndroidPlatform.java#L137](https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/AndroidPlatform.java#L137). For the non-SAF path, I call `super.stat()` and it works fine. It seems to me that the problem is in the override method code.

**Comment by proninyaroslav** [comment]
`1.2.2.0` still has this problem.

**Comment by proninyaroslav** [comment]
Still here, `1.3.0-alpha-5`.

**Comment by aldenml** [comment]
https://github.com/aldenml/libtorrent4j/issues/89#issuecomment-653705618
