### ISSUE TITLE
crash when call SessionManager.start() on Samsung devices

### ISSUE THREAD

**Issue by xin9ge** [aldenml/libtorrent4j#51]
I got the log。What's the cause of this problem? or is it possible you give me the `so` file without symbols striped so I can debug it myself?

pid: 6747, tid: 6747  >>> com.xxoo.intl:DownloadService <<<
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr c38d98e8
  r0 0000003f  r1 ffbf8dd4  r2 00000000  r3 c3b63000
  r4 c3f2b4c0  r5 c3f2b4c0  r6 c56bcb34  r7 00000000
  r8 e5195c2c  r9 c3f7f300  10 e5195c34  fp ffbf8db0
  ip c3acf0f4  sp ffbf8d90  lr c3928770  pc c38d98e8  cpsr 200f0010
  d0  0000000000000000  d1  0000000000000000
  d2  0000008000000080  d3  0000008000000080
  d4  0c0f0e0d0c0f0e0d  d5  0c0f0e0d0c0f0e0d
  d6  1190d8f7b17491a8  d7  62174e39c8cb868d
  d8  0000000000000000  d9  0000000000000000
  d10 0000000000000000  d11 0000000000000000
  d12 0000000000000000  d13 0000000000000000
  d14 0000000000000000  d15 0000000000000000
  d16 0000000000000000  d17 0000000000000000
  d18 0000000000000000  d19 5cc91b6900000000
  d20 edbd8ac1edbd8ac1  d21 edbd8ac1edbd8ac1
  d22 0000090900000018  d23 0000008000000080
  d24 0000000000ffffeb  d25 0000000001000000
  d26 0000000000000000  d27 0000000000000001
  d28 0000000000000000  d29 0000000001000000
  d30 412176649172527a  d31 9f9e9d9c9b9a9998
  scr 60000011

 #00  pc 0038a8e8  /data/app/com.xxoo.intl-wL4hMkbYp6Z3ba4GlKMPUw==/lib/arm/libtorrent4j-1.2.0.22.so
    #01  pc 003d9770  /data/app/com.xxoo.intl-wL4hMkbYp6Z3ba4GlKMPUw==/lib/arm/libtorrent4j-1.2.0.22.so

all threads dump:
[DEBUG] enter dumpAllThreadsIntoFileFunc, fd: 118, overridedMalloc: 0
[DEBUG] dumpArtThreadsInternal: 118
[DEBUG] found JavaVMExt: 0xe52698c0, index: 90, string: 4
[DEBUG] aborting: 0xe50bb320, 0
[DEBUG] Dump: 0x0, DumpState: 0xe4fb406d, DumpJavaStack: 0xe4fb7689
[DEBUG] currentThread: 0xe51f9000, pid: 6925
[DEBUG] ThreadList: 0xe521e000
[DEBUG] ForEach: 0xe4fc9ddd
[DEBUG] cerr: 0xd68abda0
[DEBUG] ForEach begin
[DEBUG] thread 0xe51f9000 dumping ...
"main" prio=5 tid=1 Native
  | group="" sCount=0 dsCount=0 flags=0 obj=0x74fe1160 self=0xe51f9000
  | sysTid=6747 nice=0 cgrp=default sched=0/0 handle=0xe986c4a8
  | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
  | stack=0xff3fe000-0xff400000 stackSize=8MB
  | held mutexes=
  at org.libtorrent4j.swig.libtorrent_jni.new_session__SWIG_0(libtorrent_jni.java)
  at org.libtorrent4j.swig.session.<init>(session.java:39)
  at org.libtorrent4j.SessionManager.start(SessionManager.java:97)
........

**Comment by aldenml** [comment]
can you try the latest version `1.2.1.0`?

**Comment by aldenml** [comment]
try the latest version and feel free to reopen
