### ISSUE TITLE
[Android][POSIX wrapper] Native crash if open() function returns -1

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#52]
Hello. This happens if you remove a torrent while downloading. At this point, a POSIX call to `open()` occurs, which returns `-1` because the required file doesn't exist.
As I understand it, the reason for the crash is to return `-1` from `open()` function. I simulated it artificially:
```Java
@Override
public int open(String path, int flags, int mode) {
    return -1;
}
```
and it also led to the crash
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 7306 (Thread-45), pid 7191 (retorrent.debug)
```
Tested on Android 9 and 10.

**Comment by proninyaroslav** [comment]
1.2.2.0 still has this problem.

**Comment by aldenml** [comment]
https://github.com/aldenml/libtorrent4j/issues/89#issuecomment-653705618
