### ISSUE TITLE
[Android][POSIX wrapper] Periodic `Try again` (code 11) error during downloading

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#58]
This happens with the default implementation of `posix_wrapper`:
```
file_error_alert: disk error: (11) Try again [write : file_open]
```

**Comment by aldenml** [comment]
ACK

**Comment by proninyaroslav** [comment]
Not seen in `1.3.0-alpha-5`, but it takes more time for tests.

**Comment by aldenml** [comment]
https://github.com/aldenml/libtorrent4j/issues/89#issuecomment-653705618
