### ISSUE TITLE
android 8.1 pasting tracker list says invalid 

### ISSUE THREAD

**Issue by blackholeearth** [aldenml/libtorrent4j#59]
Apk:Libretorrent

İ am copy pasting   trackers from this url of txt file 

Url: 
    https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt

To a torrent  menu>add tracker. İt says invalid.  . When i rotate phone  Tex box changes to white and accept s itss.  

But in vertical orientation it fails.

**Comment by aldenml** [comment]
Hi @blackholeearth, I believe this issue belongs to `Libretorrent`, not here
