### ISSUE TITLE
Some questions about 1.3.0-alpha-3

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#85]
1) There are no following methods and fields and I also didn't find a replacement for them:
   - `add_torrent_params::set_disabled_storage`
   - `AnnounceEndpoint::{fails, isWorking, updating, message}`
   - `libtorrent::generate_fingerprint`
   - `libtorrent::read_session_params`
   - `peer_info::getPieces` 
   - `SessionManager::saveState` (and in `SessionHandle`)
   - `SettingsPack::{broadcastLSD, cacheSize}`
   - `settings_pack::bool_types::upnp_ignore_nonrouters`
   - `TorrentBuilder::OPTIMIZE_ALIGNMENT`

3) Should I use `InfoHash::getBest` instead of `InfoHash::getV1`? As far as I understand, now a torrent may not contain SHA-1?
4) I also get error when building gradle:
```
error: cannot access AnnounceEndpoint
import org.libtorrent4j.AnnounceEndpoint;
                       ^
  bad class file: /home/yaroslav/data/.gradle/caches/transforms-2/files-2.1/b37e8e65b5152dcc31630689db47a240/jetified-libtorrent4j-1.3.0-alpha-3.jar(org/libtorrent4j/AnnounceEndpoint.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
Android projects use Java 8. Using Java 11 is very problematic:
```
> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> javax/xml/bind/JAXBException
```

**Comment by aldenml** [comment]
1) A lot of that has been deprecated in `master`, take a look at `libtorrent`, but I will review for some of them (like `generate_fingerprint`).
2) That depends, now we need to take into account torrents V2, and maybe "best" is not what are you looking for.
3) Let me see what I can do on the java version.

**Comment by proninyaroslav** [comment]
Many of the above are critical, I need to understand what I have to remove and what I can replace with alternative methods. I can’t remove much of this. Can I figure this out from the `libtorrent` changelogs or is the code documented for deprecated methods?

**Comment by aldenml** [comment]
I think that looking at the `libtorrent` master branch is the best option (and should be enough), but you know, it's C++.

**Comment by proninyaroslav** [comment]
C++ will not be a problem, thanks. I hope you restore API that is not deprecated in `libtorrent`, but for some reason it's not in `libtorrent4j`.

**Comment by proninyaroslav** [comment]
Most of the problems have been resolved. There are only those methods that I would like to return in `libtorretn4j`:
   - `AnnounceEndpoint::{fails, isWorking, updating, message}`
   - `libtorrent::read_session_params` (only `write_session_params`)
   - `peer_info::getPieces`
   - `libtorrent::generate_fingerprint`

A couple of questions, if you may:
1) As far as I understand `add_torrent_params::set_disabled_storage` no longer needed to fetch a magnet?
2)  I use `Sha1Hash` to identify a torrent, including storing metadata in the DB. Do I understand correctly that `getBest()` will always return `InfoHash v1` (SHA-1) for old torrents, since they were created without the support of `InfoHash v2`?

After the build problem is fixed (due to Java 11) I will fully test it again.

**Comment by aldenml** [comment]
@proninyaroslav I'm close to release alpha-3 with https://github.com/aldenml/libtorrent4j/pull/86

- You need to look at `AnnounceInfohash` instead of `AnnounceEndpoint`
- restored `(read|write)_session_params as static methods in `session_params`
- restored `peer_info::getPieces`
- restored `generate_fingerprint`

1) Well, I removed it because I think that was hurting, I think it's better to have a custom "real" location to save the bits that result from the magnet download. I need more time to test it.
2) You are right.

Give it a try and let me know the results, thanks!

**Comment by proninyaroslav** [comment]
@aldenml `AnnounceEndpoint` contains 2 methods for `v1` and `v2`. Probably if `v2` is not supported, then `infohashV2()` method will return `v1`? Or will it just contain null pointer?

**Comment by proninyaroslav** [comment]
I also noticed the `opendir` call in `posix_wrapper`. Is it possible to implement this under SAF? This requires returning a pointer to `struct dirent`, while in SAF I can only get FD.

**Comment by aldenml** [comment]
@proninyaroslav, for what I see, not null, just an empty struct (all to zero), I imagine the client needs to know if that makes sense. This is very new btw, I don't think any major client is using V2.

I believe you are right, it's not possible to use SAF for opendir, but we need to find a way because that's used for torrent creations.

**Comment by proninyaroslav** [comment]
> but we need to find a way because that's used for torrent creations.

Internally, this structure uses `inode`, which is not possible for SAF. The only thing that comes to my mind is to create a hierarchy of fake files with zero length, inside the app `data` directory, the real files of nonzero length will be stored in SAF, of course. Perhaps this will not work, because it will have zero length, for this we need to know for what specific purpose it is used in `libtorrent`. Maybe you have other thoughts and I will be glad to hear them.
