### ISSUE TITLE
[Android][POSIX wrapper] Add `renameat` syscall to support file moving

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#89]
Hi. One of my application users informed me that he was unable to move the torrent to external storage. I decided to make strace and as it turned out, `libtorrent` uses the `renameat` system call to move files:
```
renameat(AT_FDCWD, 
"/storage/emulated/0/CCleaner v5.63.7540 RePack+Portable by Dodakaedr/Silent unpack Business.cmd", AT_FDCWD, 
"/saf_root(com.android.externalstorage.documents/tree/home%3A);/CCleaner v5.63.7540 RePack+Portable by Dodakaedr/Silent unpack Business.cmd") 
= -1 ENOENT (No such file or directory)
```
This call is not in `posix_wrapper`. I tested this on `libtorrent4j 1.2.3.0` and `1.3.0-alpha-5`.

**Comment by aldenml** [comment]
Well, months have passed and with the latest news from Android 11, I believe the chances of having a long term solution for a free storage space are diminishing.

I will drop support for this and concentrate in tracking libtorrent `master` with Torrents V2 and WebTorrent support.

@proninyaroslav I understand the impact on your project, but I just can't commit to it.

for ref: https://developer.android.com/preview/privacy/storage#directory-access

**Comment by proninyaroslav** [comment]
@aldenml I understand you. Google has taken a step towards security, we can't do anything about it.
