### ISSUE TITLE
Migrate to libtorrent4j

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#9]
Hi. Do I understand correctly that `jlibtorrent` is dead and I should switch to `libtorrent4j`? As far as I understand the code base remains the same and it will not cause problems?

**Comment by aldenml** [comment]
Well, you know how open source is, It can be a little rough at the beginning. I wanted to have a name less tied to a brand, then the project and package rename. I have yet to figure out how to properly support this, but in the meantime I can keep it in sync with the `libtorrent 1.2.X` branch.

I hope it's just a search and replace in your case, but you know, it's a high risk at this moment.

**Comment by proninyaroslav** [comment]
Thank you for not quitting the project. I will migrate to libtorrent4j in my application soon.

**Comment by aldenml** [comment]
Good, report back here any issues you find.
