### ISSUE TITLE
Do you have these boost 1.73.0 build issues too? (error: feature "lto" : "off" "on" "gold" : "composite" "propagated" "link-incompatible")

### ISSUE THREAD

**Issue by gubatron** [aldenml/libtorrent4j#90]
It seems something changed with boost 1.73 and `lto` compiler features. I wonder if you're also having issues building with boost 1.73.0, I notice you no longer download the boost libraries from their mirror, instead you clone the repo.

Did you come across this issue?

```
LIBTORRENT_ROOT = /Users/gubatron/src/libtorrent
/Users/gubatron/src/boost_1_73_0/tools/build/src/build/feature.jam:140: in feature from module feature
error: feature already defined:
error: in feature declaration:
error: feature "lto" : "off" "on" "gold" : "composite" "propagated" "link-incompatible"
Jamfile:56: in load-aux from module Jamfile</Users/gubatron/workspace.frostwire/frostwire-jlibtorrent/swig>
/Users/gubatron/src/boost_1_73_0/tools/build/src/build/project.jam:378: in load-jamfile from module project
/Users/gubatron/src/boost_1_73_0/tools/build/src/build/project.jam:64: in load from module project
/Users/gubatron/src/boost_1_73_0/tools/build/src/build/project.jam:142: in project.find from module project
/Users/gubatron/src/boost_1_73_0/tools/build/src/build-system.jam:618: in load from module build-system
/Users/gubatron/src/boost_1_73_0/tools/build/src/kernel/modules.jam:295: in import from module modules
/Users/gubatron/src/boost_1_73_0/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/Users/gubatron/src/boost_1_73_0/boost-build.jam:17: in module scope from module
```

I suppose it refers to this part of the `JamFile` back at jlibtorrent

```
feature lto : off on gold : composite propagated link-incompatible ;
feature.compose <lto>on : <cxxflags>-flto <linkflags>-flto ;
feature.compose <lto>gold : <cxxflags>-flto <linkflags>-flto
    <linkflags>-fuse-ld=gold ;
```

Sucks how overly complex this C++ world is and how they keep changing and breaking shit.

**Comment by gubatron** [comment]
On Boost's documentation there's hope!

>The programming language is proprietary and not really a joy to use. It is no competitor to popular scripting languages like Javascript or Python. The developers of Boost.Build recognize it and work on another version of Boost.Build based on Python.

**Comment by gubatron** [comment]
I ended up removing that option altogether, which in the end wasn't being used. Couldn't figure out a way to get that `feature` definition to compile with 1.73.0's `b2`

**Comment by aldenml** [comment]
I also removed the feature
